project_id = "shdmcrozknktngheopik"

[functions.magic-link-login]
verify_jwt = false

[functions.competitor-admin]
verify_jwt = false

[functions.cvm-manager-search]
verify_jwt = false

[functions.rag-ingest]
verify_jwt = false

[functions.rag-chat]
verify_jwt = false

[functions.fnet-fetch]
verify_jwt = false